theme: jekyll-theme-minimal
title: Data Preprocessing Helper
description: A project that helps you preprocess your time-series data for annoying gaps and value-of-change format (data in different time intervals) such as data from BMS, CCMS and other control systems
author: Howard Cheung
plugins:
  - jekyll-seo-tag